import fs from 'fs/promises';
import path from 'path';
import { layoutService } from './layoutService.js';
import { exportService } from './exportService.js';
import { Layout } from '../types/schema.js';

const DOCS_DIR = process.env.DOCS_DIR || './docs';
const PREVIEWS_DIR = path.join(DOCS_DIR, 'previews');

interface GalleryItem {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  entityCount: number;
  preview: string | null;
  exports: string[];
}

interface GalleryIndex {
  generatedAt: string;
  layouts: GalleryItem[];
}

async function ensureDirectories() {
  await fs.mkdir(DOCS_DIR, { recursive: true });
  await fs.mkdir(PREVIEWS_DIR, { recursive: true });
}

async function generatePreview(layout: Layout): Promise<string | null> {
  const previewPath = path.join(PREVIEWS_DIR, `${layout.slug}.png`);
  
  try {
    const svg = exportService.layoutToSvg(layout, {
      formats: ['png'],
      includeGrid: true,
      includeDimensions: false,
      paperSize: layout.settings.pageSize,
      orientation: 'landscape',
      scaleLabel: '',
      dpi: 72,
    });
    
    const sharp = (await import('sharp')).default;
    const buffer = Buffer.from(svg);
    await sharp(buffer, { density: 72 })
      .resize(400, 300, { fit: 'inside' })
      .png()
      .toFile(previewPath);
    
    return `previews/${layout.slug}.png`;
  } catch (error) {
    console.error(`Failed to generate preview for ${layout.slug}:`, error);
    return null;
  }
}

async function buildGallery(): Promise<void> {
  await ensureDirectories();
  
  const layouts = await layoutService.listLayouts();
  const galleryItems: GalleryItem[] = [];
  
  for (const summary of layouts) {
    const layout = await layoutService.getLayout(summary.slug);
    if (!layout) continue;
    
    const preview = await generatePreview(layout);
    const exports = await exportService.listExports(summary.slug);
    
    galleryItems.push({
      id: summary.id,
      name: summary.name,
      slug: summary.slug,
      updatedAt: summary.updatedAt,
      entityCount: summary.entityCount,
      preview,
      exports,
    });
  }
  
  const index: GalleryIndex = {
    generatedAt: new Date().toISOString(),
    layouts: galleryItems,
  };
  
  // Write index.json
  await fs.writeFile(
    path.join(DOCS_DIR, 'index.json'),
    JSON.stringify(index, null, 2),
    'utf-8'
  );
  
  // Write static gallery files
  await writeGalleryHtml();
  await writeGalleryCss();
  await writeGalleryJs();
}

async function writeGalleryHtml(): Promise<void> {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Floorplan Gallery</title>
  <link rel="stylesheet" href="gallery.css">
</head>
<body>
  <header>
    <h1>Floorplan Gallery</h1>
    <p class="subtitle">Browse and download layout exports</p>
  </header>
  <main>
    <div id="gallery" class="gallery-grid">
      <p class="loading">Loading layouts...</p>
    </div>
  </main>
  <footer>
    <p>Generated by Floorplan Builder</p>
  </footer>
  <script src="gallery.js"></script>
</body>
</html>`;
  
  await fs.writeFile(path.join(DOCS_DIR, 'index.html'), html, 'utf-8');
}

async function writeGalleryCss(): Promise<void> {
  const css = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  background: #f5f5f5;
  color: #333;
  min-height: 100vh;
}

header {
  background: #1a1a2e;
  color: white;
  padding: 2rem;
  text-align: center;
}

header h1 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
}

.subtitle {
  opacity: 0.8;
}

main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1.5rem;
}

.layout-card {
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: transform 0.2s, box-shadow 0.2s;
}

.layout-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
}

.preview-container {
  aspect-ratio: 4/3;
  background: #eee;
  display: flex;
  align-items: center;
  justify-content: center;
}

.preview-container img {
  width: 100%;
  height: 100%;
  object-fit: contain;
}

.no-preview {
  color: #999;
  font-size: 0.9rem;
}

.card-content {
  padding: 1rem;
}

.card-content h2 {
  font-size: 1.1rem;
  margin-bottom: 0.5rem;
}

.card-meta {
  font-size: 0.85rem;
  color: #666;
  margin-bottom: 1rem;
}

.exports-list {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
}

.export-link {
  display: inline-block;
  padding: 0.25rem 0.75rem;
  background: #e94560;
  color: white;
  text-decoration: none;
  border-radius: 4px;
  font-size: 0.85rem;
  text-transform: uppercase;
}

.export-link:hover {
  background: #ff6b6b;
}

.loading, .empty-state {
  text-align: center;
  padding: 3rem;
  color: #666;
}

footer {
  text-align: center;
  padding: 2rem;
  color: #666;
  font-size: 0.9rem;
}
`;
  
  await fs.writeFile(path.join(DOCS_DIR, 'gallery.css'), css, 'utf-8');
}

async function writeGalleryJs(): Promise<void> {
  const js = `(async function() {
  const gallery = document.getElementById('gallery');
  
  try {
    const response = await fetch('index.json');
    const data = await response.json();
    
    if (data.layouts.length === 0) {
      gallery.innerHTML = '<p class="empty-state">No layouts found. Create some layouts in the editor!</p>';
      return;
    }
    
    gallery.innerHTML = data.layouts.map(layout => \`
      <article class="layout-card">
        <div class="preview-container">
          \${layout.preview 
            ? \`<img src="\${layout.preview}" alt="\${layout.name} preview">\`
            : '<span class="no-preview">No preview available</span>'
          }
        </div>
        <div class="card-content">
          <h2>\${layout.name}</h2>
          <p class="card-meta">
            \${layout.entityCount} entities &bull; 
            Updated \${new Date(layout.updatedAt).toLocaleDateString()}
          </p>
          <div class="exports-list">
            \${layout.exports.map(exp => \`
              <a href="../exports/\${layout.slug}/\${exp}" class="export-link" download>
                \${exp.split('.').pop().toUpperCase()}
              </a>
            \`).join('')}
          </div>
        </div>
      </article>
    \`).join('');
  } catch (error) {
    gallery.innerHTML = '<p class="empty-state">Failed to load gallery. Make sure index.json exists.</p>';
    console.error('Gallery load error:', error);
  }
})();
`;
  
  await fs.writeFile(path.join(DOCS_DIR, 'gallery.js'), js, 'utf-8');
}

async function getGalleryIndex(): Promise<GalleryIndex | null> {
  try {
    const content = await fs.readFile(path.join(DOCS_DIR, 'index.json'), 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

export const galleryService = {
  buildGallery,
  getGalleryIndex,
};
